# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: 'Requiem Labs'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build_Master_Version_Number
  displayName: Build Master Version Number
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: Build_Master_Version_Number
    displayName: Build Master Version Number
    variables:
       buildnum: $[counter(variables['patch'], 0)]
       fullbuildnum: $(major).$(minor).$(patch).$(buildnum)
    steps:
      - powershell: |
           echo "##vso[build.updatebuildnumber]$env:MAJOR.$env:MINOR.$env:PATCH.$env:BUILDNUM"
        name: SetMasterBuildName

- stage: Test_Build_App_Version
  displayName: Test Stage - Versioning
  jobs:
  - job: Build_App
    variables:
      fullbuildnum: stageDependencies.Build_Master_Version_Number.Build_Master_Version_Number.outputs['fullbuildnum']
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Build is $($env:fullbuildnum)"'
        errorActionPreference: 'continue'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/Labmin.Api.csproj'

# steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
