# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: 'Requiem Labs Build'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: GitVersion
    steps:
    - task: gitversion/setup@0
      inputs:
        versionSpec: '5.x'
    - task: gitversion/execute@0
      inputs:
        updateAssemblyInfo: true
    - script: |
            echo Major: $(GitVersion.Major)
            echo Minor: $(GitVersion.Minor)
            echo Patch: $(GitVersion.Patch)
            echo PreReleaseTag: $(GitVersion.PreReleaseTag)
            echo PreReleaseTagWithDash: $(GitVersion.PreReleaseTagWithDash)
            echo PreReleaseLabel: $(GitVersion.PreReleaseLabel)
            echo PreReleaseNumber: $(GitVersion.PreReleaseNumber)
            echo WeightedPreReleaseNumber: $(GitVersion.WeightedPreReleaseNumber)
            echo BuildMetaData: $(GitVersion.BuildMetaData)
            echo BuildMetaDataPadded: $(GitVersion.BuildMetaDataPadded)
            echo FullBuildMetaData: $(GitVersion.FullBuildMetaData)
            echo MajorMinorPatch: $(GitVersion.MajorMinorPatch)
            echo SemVer: $(GitVersion.SemVer)
            echo LegacySemVer: $(GitVersion.LegacySemVer)
            echo LegacySemVerPadded: $(GitVersion.LegacySemVerPadded)
            echo AssemblySemVer: $(GitVersion.AssemblySemVer)
            echo AssemblySemFileVer: $(GitVersion.AssemblySemFileVer)
            echo FullSemVer: $(GitVersion.FullSemVer)
            echo InformationalVersion: $(GitVersion.InformationalVersion)
            echo BranchName: $(GitVersion.BranchName)
            echo EscapedBranchName: $(GitVersion.EscapedBranchName)
            echo Sha: $(GitVersion.Sha)
            echo ShortSha: $(GitVersion.ShortSha)
            echo NuGetVersionV2: $(GitVersion.NuGetVersionV2)
            echo NuGetVersion: $(GitVersion.NuGetVersion)
            echo NuGetPreReleaseTagV2: $(GitVersion.NuGetPreReleaseTagV2)
            echo NuGetPreReleaseTag: $(GitVersion.NuGetPreReleaseTag)
            echo VersionSourceSha: $(GitVersion.VersionSourceSha)
            echo CommitsSinceVersionSource: $(GitVersion.CommitsSinceVersionSource)
            echo CommitsSinceVersionSourcePadded: $(GitVersion.CommitsSinceVersionSourcePadded)
            echo UncommittedChanges: $(GitVersion.UncommittedChanges)
            echo CommitDate: $(GitVersion.CommitDate)
      displayName: "Show Version Numbers"
    